// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newsletter.Api.Databases;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Newsletter.Api.Migrations
{
    [DbContext(typeof(NewsletterDbContext))]
    partial class NewsletterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Newsletter.Api.Databases.TestSendingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReceiveOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReceivedEmail")
                        .HasColumnType("text");

                    b.Property<string>("SendingEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TestSendingMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
